name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
      - name: Publish Bundle
        uses: actions/upload-artifact@v4
        with:
          name: db2xls-bundle.jar
          path: db2xls-bundle/target/db2xls-bundle-*.jar
